# Generated by Django 3.0.8 on 2020-08-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChooseMostSold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_bike_id', models.IntegerField(verbose_name='id велосипеда №1')),
                ('second_bike_id', models.IntegerField(verbose_name='id велосипеда №2')),
            ],
        ),
    ]
