# Generated by Django 3.0.8 on 2020-08-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ваше имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Ваша почта')),
                ('phone', models.IntegerField(verbose_name='Ваш телефон')),
            ],
        ),
    ]
