# Generated by Django 3.0.8 on 2020-08-09 07:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ваше имя')),
                ('bike_name', models.CharField(blank=True, default='Не задано', max_length=30, verbose_name='Название велосипеда')),
                ('text', models.TextField(verbose_name='Текст вашего отзыва')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(6)], verbose_name='Ваша оценка по 5 балльной шкале')),
            ],
            options={
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
