# Generated by Django 3.0.8 on 2020-08-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='bike_name',
        ),
        migrations.RemoveField(
            model_name='review',
            name='date',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(max_length=200, verbose_name='Текст вашего отзыва'),
        ),
    ]
